version: '3'
services:
  top-api:
    image: top-api:latest
    restart: always
    ports:
      - 3005:3000
    volumes:
      - ./.env:/opt/app/.env


  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db